version: '2'
services:
    dreszcz-app:
        image: dreszcz
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dreszcz-mysql:3306/dreszcz?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dreszcz-mysql:
        extends:
            file: mysql.yml
            service: dreszcz-mysql
